name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create Deployment Files
        shell: bash
        env:
          LOKI: ${{ secrets.LOKI_URL }}
          ENVARS: ${{ secrets.ENVIRONMENT_VARIABLES }}
          AINV: ${{ secrets.ANSIBLE_INVENTORY }}
          APKEY: ${{ secrets.ANSIBLE_PRIVATE_KEY }}
        run: |
          echo "$ENVARS" > ./ansible/.env
          echo "$AINV" > ./ansible/inventory.ini
          echo "$APKEY" > ./ansible/key.pem
          chmod 400 ./ansible/key.pem
          sed -i "s#LOKI-REPLACE-ME#$LOKI#g" ./ansible/docker-compose.yml

      - name: Build & Publish Container
        run: |
          docker build -t witnet/data-feed-status-bot:latest -f ./ansible/docker/dockerfile .
          docker push witnet/data-feed-status-bot:latest

      - name: Deploy with Ansible
        shell: bash
        run: |
          cd ansible
          export ANSIBLE_CONFIG=./ansible.cfg
          export ANSIBLE_FORCE_COLOR=True
          export ANSIBLE_STDOUT_CALLBACK=yaml
          export FORCE_COLOR=1
          export TERM=xterm-color
          ansible-playbook ./helper/docker-playbook.yml -vv
          ansible-playbook playbook.yml -vv
